version: "3.9"
services:
  postgres:
    image: veventumt/mypg:mypg
    environment:
      POSTGRES_DB: "vktest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cassandra:
    image: veventumt/vk-cassandra:vk-cassandra
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  vktest:
    image: veventumt/vktest:0.0.8
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cassandra
    links:
      - redis

volumes:
  pgdata:
  cassandra_data:
  redis_data:
