version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "vktest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  pgdata:
  cassandra_data:

  #spring-app:
   # image: veventumt/authforstock
    #ports:
     # - "8080:8080"
    #depends_on:
     # - postgres