spring:
  cache:
    redis:
      time-to-live: 10000000
  application:
    name: VkTestApplication
  datasource:
    url: jdbc:postgresql://postgres:5432/vktest
    driverClassName: org.postgresql.Driver
    username: "admin"
    password: "admin"
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: vk
    schema-action: create_if_not_exists
    contact-points: cassandra
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    redis:
      port: 6379
      host: redis
token:
  signing:
    key: HldPJxTjwhAVfklMnZeLjqWzyXrpviDuNUCRtaYIBQoGSOgsKcFmbE